### PR TITLE
Changed drops amount + No rust drops available fix

### PR DESCRIPTION
**Pull request by BoTeQX**

### CODE REVIEW

**Comment by BoTeQX** [comment]
> How use this fix?

Just donwload my commit and follow installation with npm
image

**Comment by Damian2623232** [comment]
Thank you

**Comment by 4683597** [comment]
npm install doesn't work for me

**Comment by skupfer** [comment]
Works

_(but not fully functional. Started watching nmplol for several tries and said no progress and skipped. Luckily noticed it in time since his skin got removed and I went to manual watching. Maybe an issue with BTTV addon which needs adapted paths?)_

**Comment by culloa1** [comment]
any fix for this now? it wont find channel anymore, restarted and now its not detecting I logged in.

**Review by Zaarrg — COMMENTED** [review]
Added your fix as [commit](https://github.com/Zaarrg/TTVDropBot/commit/615a5f55458299a80bc301236d74d4543921182d). No need to merge it anymore.

**Pull request closed without merging**
